# Generated by Django 3.1.7 on 2021-03-05 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0002_auto_20210303_2353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagina1',
            new_name='Model1',
        ),
    ]
